[package]
name = "tests_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
tokio = { version = "1.43.0", features = ["full"] }
async-trait = "0.1.86"
indexmap = "2.7.1"
futures = "0.3.31"
libc = "0.2.1"